language: php

php:
 - 5.3
 - 5.4

before_install:
 - composer self-update
 - composer install --dev -o

before_script:
 - mkdir -p build/logs
 - cd tests

script:
 - phpunit --coverage-clover ../build/logs/clover.xml
 
after_script:
  - php vendor/bin/coveralls -v
